
plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
    id 'idea'
    id 'maven-publish'
}

def prop = { key -> project.findProperty(key).toString() }

def modId = prop('modId')
def modVersion = prop('modVersion')
def mcVersion = prop('mcVersion')

version = "${mcVersion}-${modVersion}"
group = prop('group')

base {
    archivesName = modId
}

repositories {
    maven {
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }
    maven { url = 'https://maven.parchmentmc.org' }
    mavenCentral()
}

neoForge {
    version = prop('neoForgeVersion')

    parchment {
        minecraftVersion = mcVersion
        mappingsVersion = prop('mappingsVersion')
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
        }

        client {
            client()
            gameDirectory = file('run')
        }

        server {
            server()
            gameDirectory = file('run-server')
        }

        data {
            data()
            gameDirectory = file('run')
            programArguments.addAll(
                    '--mod', modId,
                    '--all',
                    '--output', file('src/generated/resources').absolutePath,
                    '--existing', file('src/main/resources').absolutePath,
                    '--existing-mod', 'dynamictrees',
                    '--existing-mod', 'vanillabackport'
            )
        }
    }

    mods {
        "${modId}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def replaceProperties = [
            mod_version: prop('modVersion'),
            mod_description: prop('mod_description')
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}
