plugins {
    id 'dtvanillabackport.neoforge-conventions'
}

def prop = { key -> project.findProperty(key).toString() }
def localVanillaBackportBeta = file('C:/Users/ykkim/Downloads/VanillaBackport-neoforge-1.21.1-1.2.0.2629.6.jar')

dependencies {
    implementation "maven.modrinth:vdjF5PL5:${prop('dynamicTreesVersionId')}"
    implementation localVanillaBackportBeta.exists() ? files(localVanillaBackportBeta) : "maven.modrinth:6xwxDTgf:${prop('vanillaBackportVersionId')}"
    implementation "maven.modrinth:i6fiqm5y:${prop('platformVersionId')}"
}

tasks.named('jar') {
    manifest {
        attributes(
                'Specification-Title': project.name,
                'Specification-Vendor': 'dannykim',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'dannykim',
                'Implementation-Timestamp': java.time.format.DateTimeFormatter.ISO_INSTANT.format(java.time.Instant.now())
        )
    }
}
