plugins {
    id 'dtvanillabackport.forge-conventions'
}

def prop = { key -> project.findProperty(key).toString() }
def localVanillaBackportBeta = file('C:/Users/ykkim/Downloads/VanillaBackport-forge-1.20.1-1.2.0.2629.6.jar')

dependencies {
    implementation fg.deobf("maven.modrinth:vdjF5PL5:${prop('dynamicTreesVersionId')}")
    implementation fg.deobf(localVanillaBackportBeta.exists() ? files(localVanillaBackportBeta) : "maven.modrinth:6xwxDTgf:${prop('vanillaBackportVersionId')}")
    implementation fg.deobf("maven.modrinth:i6fiqm5y:${prop('platformVersionId')}")
}

tasks.named('jar') {
    finalizedBy 'reobfJar'
    manifest {
        attributes(
                'Specification-Title': project.name,
                'Specification-Vendor': prop('modAuthor'),
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': prop('modAuthor'),
                'Implementation-Timestamp': java.time.format.DateTimeFormatter.ISO_INSTANT.format(java.time.Instant.now()),
                'MixinConfigs': 'dtvanillabackport.mixins.json'
        )
    }
}
