modName=Dynamic Trees for VanillaBackport
modId=dtvanillabackport
modVersion=1.5.0
modAuthor=dannykim
group=com.dannykim.dtvanillabackport
mod_description=Compatibility addon between Dynamic Trees and VanillaBackport

mcVersion=1.20.1
forgeVersion=47.4.0

dynamicTreesVersionId=JAF7MM1b
vanillaBackportProjectId=6xwxDTgf
vanillaBackportVersionId=u8YPiN39
platformProjectId=i6fiqm5y
platformVersionId=aWxR0Ksa

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
