modName=Dynamic Trees for VanillaBackport
modId=dtvanillabackport
modVersion=1.6.0
group=com.dannykim.dtvanillabackport
mod_description=Compatibility addon between Dynamic Trees and VanillaBackport

mcVersion=1.21.1
neoForgeVersion=21.1.234
mappingsVersion=2024.11.17

dynamicTreesVersionId=G4uJ0UA0
vanillaBackportVersionId=rUSWdBok
platformVersionId=v7P0nBi2

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
