modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${mod_id}.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dynamictrees"
mandatory=true
versionRange="[${dynamic_trees_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="vanillabackport"
mandatory=true
versionRange="[${vanilla_backport_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="platform"
mandatory=true
versionRange="[${platform_version},)"
ordering="AFTER"
side="BOTH"
