modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="dtvanillabackport"
version="${mod_version}"
displayName="Dynamic Trees–VanillaBackport"
authors="dannykim"
description='''${mod_description}'''

[[dependencies.dtvanillabackport]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.dtvanillabackport]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.dtvanillabackport]]
modId="dynamictrees"
mandatory=true
versionRange="[1.4.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtvanillabackport]]
modId="vanillabackport"
mandatory=true
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtvanillabackport]]
modId="platform"
mandatory=true
versionRange="[1.3.4,)"
ordering="AFTER"
side="BOTH"
